const products=[
  {id:'small',name:'صفا مكة — 330 مل',detail:'40 عبوة في الكرتون',price:1.500,tag:'للضيافة والمناسبات',art:'330 مل',image:'assets/safa-330.webp'},
  {id:'medium',name:'صفا مكة — 600 مل',detail:'28 عبوة في الكرتون',price:2.000,tag:'لليوم الطويل',art:'600 مل',image:'assets/safa-600.webp'},
  {id:'bundle',name:'باقة 5 كراتين',detail:'600 مل · 28 عبوة لكل كرتون',price:9.000,tag:'كمية أكثر للبيت والعمل',art:'600 مل',image:'assets/safa-600.webp'}
];
const cart=new Map();const $=id=>document.getElementById(id);const format=n=>n.toFixed(3)+' د.ك';let active=null,lastFocus=null;
$('product-grid').innerHTML=products.map(p=>`<article class="product-card"><div class="product-art"><span class="product-size">${p.art}</span><img src="${p.image}" alt="كرتون مياه صفا مكة الأصلي ${p.art}" width="600" height="350" loading="lazy">${p.id==='bundle'?'<span class="bundle-label">× 5 كراتين</span>':''}</div><div class="product-body"><span class="category">${p.tag}</span><h3>${p.name}</h3><p>${p.detail}</p><div class="product-bottom"><div class="price"><strong>${format(p.price)}</strong><small>سعر تجريبي</small></div><button class="add-button" type="button" data-add="${p.id}" aria-label="إضافة ${p.name} للسلة">+ أضف للسلة</button></div></div></article>`).join('');
function sum(){return [...cart].reduce((n,[id,q])=>n+products.find(p=>p.id===id).price*q,0)}
function renderCart(){const total=[...cart.values()].reduce((a,b)=>a+b,0);$('cart-count').textContent=total;$('cart-total').textContent=format(sum());$('checkout-start').disabled=!total;$('cart-items').innerHTML=total?[...cart].map(([id,q])=>{const p=products.find(p=>p.id===id);return `<div class="cart-item"><img class="cart-thumb" src="${p.image}" alt=""><div><strong>${p.name}</strong><small>${format(p.price)} × ${q}</small><div class="quantity"><button type="button" data-qty="${id}" data-delta="-1" aria-label="تقليل ${p.name}">−</button><b>${q}</b><button type="button" data-qty="${id}" data-delta="1" aria-label="زيادة ${p.name}">+</button><button type="button" class="remove" data-remove="${id}">حذف</button></div></div><strong>${format(q*p.price)}</strong></div>`}).join(''):'<div class="empty"><b>سلتك فارغة</b><p>اختر ما يناسبك من المنتجات وابدأ طلبك.</p><a class="text-link" href="#المنتجات" id="empty-shop">تصفّح المنتجات ←</a></div>'}
function show(id){if(active)hide(false);lastFocus=document.activeElement;active=id;$('overlay').hidden=false;$(id).classList.add('open');$(id).setAttribute('aria-hidden','false');document.body.classList.add('no-scroll');$(id).querySelector('button, input')?.focus()}
function hide(restore=true){if(!active)return;$(active).classList.remove('open');$(active).setAttribute('aria-hidden','true');active=null;$('overlay').hidden=true;document.body.classList.remove('no-scroll');if(restore)lastFocus?.focus()}
function change(id,d){const q=(cart.get(id)||0)+d;if(q<=0)cart.delete(id);else cart.set(id,q);renderCart()}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){change(add.dataset.add,1);show('cart-drawer')}const qty=e.target.closest('[data-qty]');if(qty)change(qty.dataset.qty,Number(qty.dataset.delta));const remove=e.target.closest('[data-remove]');if(remove){cart.delete(remove.dataset.remove);renderCart()}if(e.target.closest('#empty-shop'))hide(false);const info=e.target.closest('[data-info]');if(info){const delivery=info.dataset.info==='delivery';$('info-title').textContent=delivery?'التوصيل والاسترجاع':'الخصوصية والشروط';$('info-copy').textContent=delivery?'هذه صفحة توضيحية للنسخة التجريبية. مناطق التوصيل ورسومها ومواعيدها، وكذلك سياسة الاسترجاع، تُكتب وفق سياسة الوكيل الفعلية قبل الإطلاق.':'النسخة التجريبية لا تحفظ البيانات ولا ترسل النماذج لأي جهة. تضاف سياسة الخصوصية والشروط الرسمية للوكيل قبل استقبال الطلبات الحقيقية.';show('info-modal')}});
$('cart-open').onclick=()=>show('cart-drawer');$('cart-close').onclick=hide;$('checkout-close').onclick=hide;$('info-close').onclick=hide;$('overlay').onclick=hide;document.addEventListener('keydown',e=>{if(e.key==='Escape')hide();if(e.key==='Tab'&&active){const focusable=[...$(active).querySelectorAll('button:not(:disabled),input,select,textarea,a[href]')].filter(el=>el.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
$('checkout-start').onclick=()=>{if(!cart.size)return;$('checkout-form').hidden=false;$('order-success').hidden=true;$('checkout-summary').innerHTML=`<span>${[...cart.values()].reduce((a,b)=>a+b,0)} منتج في السلة</span><strong>${format(sum())}</strong>`;show('checkout-modal')};
$('checkout-form').onsubmit=e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;const data=new FormData(e.currentTarget);const name=String(data.get('name')||'').trim();const area=String(data.get('area')||'').trim();$('checkout-form').hidden=true;$('order-success').hidden=false;$('order-success').replaceChildren();const title=document.createElement('h3');title.textContent='تمت معاينة طلبك يا '+name;const p=document.createElement('p');p.textContent=`العنوان: ${data.get('governorate')}، ${area}. مجموع المنتجات ${format(sum())}. هذه محاكاة فقط؛ لم يُرسل الطلب ولم يُخصم أي مبلغ.`;const btn=document.createElement('button');btn.type='button';btn.className='button primary full';btn.textContent='العودة للمتجر';btn.onclick=()=>{cart.clear();renderCart();$('checkout-form').reset();hide()};$('order-success').append(title,p,btn);btn.focus()};
$('business-form').onsubmit=e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;const data=new FormData(e.currentTarget);$('business-feedback').textContent=`طلب ${data.get('company')} جاهز للمعاينة فقط. لا تُرسل البيانات في هذه النسخة التجريبية.`};renderCart();
